config = {}
config['mongo'] = {}
config['mongo']['host'] = '172.17.0.72'
config['mongo']['port'] = 27017

config['rdb'] = {}
config['rdb']['host'] = '127.0.0.1'
config['rdb']['port'] = 28015

refSort = {
        'genesis':1,
        'exodus':2,
        'leviticus':3,
        'numbers':4,
        'deuteronomy':5,
        'joshua':6,
        'judges':7,
        'ruth':8,
        '1 samuel':9,
        '2 samuel':10,
        '1 kings':11,
        '2 kings':12,
        '1 chronicles':13,
        '2 chronicles':14,
        'ezra':15,
        'nehemiah':16,
        'esther':17,
        'job':18,
        'psalm':19,
        'proverbs':20,
        'ecclesiastes':21,
        'song of solomon':22,
        'isaiah':23,
        'jeremiah':24,
        'lamentations':25,
        'ezekiel':26,
        'daniel':27,
        'hosea':28,
        'joel':29,
        'amos':30,
        'obadiah':31,
        'jonah':32,
        'micah':33,
        'nahum':34,
        'habakkuk':35,
        'zephaniah':36,
        'haggai':37,
        'zechariah':38,
        'malachi':39,
        'matthew':40,
        'mark':41,
        'luke':42,
        'john':43,
        'acts':44,
        'romans':45,
        '1 corinthians':46,
        '2 corinthians':47,
        'galatians':48,
        'ephesians':49,
        'philippians':50,
        'colossians':51,
        '1 thessalonians':52,
        '2 thessalonians':53,
        '1 timothy':54,
        '2 timothy':55,
        'titus':56,
        'philemon':57,
        'hebrews':58,
        'james':59,
        '1 peter':60,
        '2 peter':61,
        '1 john':62,
        '2 john':63,
        '3 john':64,
        'jude':65,
        'revelation':66
    }
refLookup = {'genesis':['gen','ge','gn'],
        'exodus':['exo','ex','exod'],
        'leviticus':['lev','le','lv'],
        'numbers':['num','nu','nm','nb'],
        'deuteronomy':['deut','dt'],
        'joshua':['josh','jos','jsh'],
        'judges':['judg','jdg','jg','jdgs'],
        'ruth':['rth','ru'],
        '1 samuel':['1 sam','1 sa'],
        '2 samuel':['2 sam','2 sa'],
        '1 kings':['1 kgs','1 ki'],
        '2 kings':['2 kgs','2 ki'],
        '1 chronicles':['1 chron','1 ch', '1 chr'],
        '2 chronicles':['2 chron','2 ch', '2 chr'],
        'ezra':['ezra','ezr'],
        'nehemiah':['neh','ne'],
        'esther':['esth','est','es'],
        'job':['job','job','jb'],
        'psalm':['pslm','ps','psa','psm','pss'],
        'proverbs':['prov','pr','prv'],
        'ecclesiastes':['eccles','ec','ecc','eccl'],
        'song of solomon':['song','so','song of songs','sos','sng'],
        'isaiah':['isa','is'],
        'jeremiah':['jer','je','jr'],
        'lamentations':['lam','la'],
        'ezekiel':['ezek','eze','ezk'],
        'daniel':['dan','da','dn'],
        'hosea':['hos','ho'],
        'joel':['joel','joe','jl'],
        'amos':['amos','am'],
        'obadiah':['obad','ob'],
        'jonah':['jnh','jonah'],
        'micah':['micah','mic'],
        'nahum':['nah','na'],
        'habakkuk':['hab','hab'],
        'zephaniah':['zeph','zep','zp'],
        'haggai':['haggai','hag','hg'],
        'zechariah':['zech','zec','zc'],
        'malachi':['mal','mal','ml'],
        'matthew':['matt','mt'],
        'mark':['mark','mrk','mk','mr'],
        'luke':['luke','luk','lk'],
        'john':['john','jn','jhn'],
        'acts':['acts','ac'],
        'romans':['rom','ro','rm'],
        '1 corinthians':['1 cor','1 co'],
        '2 corinthians':['2 cor','2 co'],
        'galatians':['gal','ga'],
        'ephesians':['ephes','eph'],
        'philippians':['phil','php'],
        'colossians':['col','col'],
        '1 thessalonians':['1 thess','1 thes', '1 th'],
        '2 thessalonians':['2 thess','2 thes', '2 th'],
        '1 timothy':['1 tim','1 ti'],
        '2 timothy':['2 tim','2 ti'],
        'titus':['titus','tit'],
        'philemon':['philem','phm'],
        'hebrews':['hebrews','heb'],
        'james':['james','jas','jm'],
        '1 peter':['1 pet','1 pe'],
        '2 peter':['2 pet','2 pe'],
        '1 john':['1 john','1 jn'],
        '2 john':['2 john','2 jn'],
        '3 john':['3 john','3 jn'],
        'jude':['jude','jud'],
        'revelation':['rev','re']}
